	dc.b "              TRY F\ TO F\[ FOR MUSICeee          "
	dc.b "ENTERf IF YOU DAREf THE CYBERPUNKS jSOUL PSYCHEDELICIDEj SCREENf A SLIGHTLY MODIFIED kIeEe \[[ PERCENT REWRITTENl VERSION OF OUR VERY FIRST DEMO SCREENf DONE ALMOST EXACTLY ] YEARS AFTER THE ORIGINALe           "
	dc.b "THE SCREEN WAS ORIGINALLY WRITTEN MAINLY BY VILMf BUT THE NEW VERSION IS MOSTLY BY ZAXe           "
	dc.b "THIS IS THE FIRST SCREEN I HAVE WRITTEN SINCE STARTING COLLEGEf WHERE I AM STUDYING MATHSf FURTHER MATHSf PHILOSOPHY AND COMPUTING AND VILM IS TAKING ARTf COMPUTING AND PHILOSOPHYe            "
	dc.b "SOME INTERESTING FACTS ABOUT THE CYBERPUNKSeeeee     "
	dc.b "IF WE STOOD ON EACH OTHERiS SHOULDERSf WE WOULD BE ] PEOPLE TALL BUT ONLY ONE PERSON WIDEeeee      "
	dc.b "WE DONiT KNOW HOW FAR WE ARE FROM THE MOONeeee     "
	dc.b "GRAVITY EXERTS ABOUT b[[ NEWTONS OF FORCE ON EACH CYBERPUNKg         "
	dc.b "IF YOU PACKAGED US TOGETHER INSTEAD OF INDIVIDUALLYf YOU WOULD SAVE ABOUT \] SQUARE FEET OF CARDBOARDf BUT WE WOULDNiT BE VERY HAPPY ABOUT ITeeee     "
	dc.b "THERE ARE PEOPLE WE COULD QUITE HAPPILY BE PACKAGED WITHeeee     "
	dc.b "ARE YOU ON DRUGSh     YOU AREf ARENiT YOUh        EVERYBODY KNOWSe         "
	dc.b "BOOg           OH DEAR IiVE JUST EMBARASSED MYSELF INTO A COMAe            "
