messg	dc.b 0
	dc.b 0
	dc.b "     THE CYBERPUNKS ^D BALLS DEMO",0
	dc.b "    WRITTEN FOR ST FORMAT MAGAZINE",0
	dc.b "            BY ZAX AND VILM",0
	dc.b 0
	dc.b 0
	dc.b 0
	dc.b 0
	dc.b "efgh INSERT AND CLR REPRESENT X Y j Zkl",0
	dc.b 0
	dc.b 0
	dc.b " klUSED ALONE i MOVE RELATIVE TO AXES",0
	dc.b "     klUSED IN CONJUNCTION WITHkl",0
	dc.b "       kl SHIFT i SPIN ON AXES",0
	dc.b "     kl CONTROL i MOVE VIEW POINT",0
	dc.b 0
	dc.b 0
	dc.b 0
	dc.b "                 ALSOkl",0
	dc.b 0
	dc.b 0
	dc.b "       ESC i RESET COeORDINATES",0
	dc.b "        F\ i F\[ i PRESET PATHS",0
	dc.b "       \ i [ i DIFFERENT OBJECTS",0
	dc.b "      Q i P FOR DIFFERENT COLOURS",0
	dc.b "             SPACE TO QUIT",0
	dc.b 0
	dc.b 0
	dc.b 0
	dc.b "       PRESS TAB FOR CONTROLS",0
	dc.b "Xe [[[  Ye [[[  Ze [[[ SXe [[[ SYe [[[",0
	dc.b "   SZe [[[ OXe [[[ OYe [[[ OZe [[[",0
ness	dc.b 0

	dc.l bufr		; Just to stop this file from building